-- Intelli Workspace (WorkDesk + ExpenseFlow) — database for intellitaxadvisors.com/employeeworkspace
-- Run once in Supabase → SQL Editor, after 003_compliance_calendar.sql. Safe to re-run.
--
-- The tables live in their own schemas (workdesk, expenseflow), NOT in public: Supabase's REST API only
-- exposes public, so these are reachable only by the server code in api/ over DATABASE_URL.
-- Columns mirror the original SQLite apps (dates as ISO text) so their queries run unchanged.

create schema if not exists wscompat;
create schema if not exists workdesk;
create schema if not exists expenseflow;
revoke all on schema wscompat, workdesk, expenseflow from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- SQLite date/time functions (used by the apps' SQL via api/_workspace/pg.py)
-- 'localtime' means India time.
-- ---------------------------------------------------------------------------
create or replace function wscompat.sq_ts(v text, mods text[]) returns timestamp
language plpgsql stable as $$
declare t timestamp; m text; n int;
begin
  if v is null then return null; end if;
  if lower(v) = 'now' then
    t := now() at time zone 'UTC';
  else
    begin
      t := replace(replace(trim(v), 'T', ' '), 'Z', '')::timestamp;
    exception when others then return null;
    end;
  end if;
  foreach m in array coalesce(mods, '{}'::text[]) loop
    m := lower(trim(m));
    if m = 'localtime' then t := (t at time zone 'UTC') at time zone 'Asia/Kolkata';
    elsif m = 'utc' then t := (t at time zone 'Asia/Kolkata') at time zone 'UTC';
    elsif m = 'start of month' then t := date_trunc('month', t);
    elsif m = 'start of year' then t := date_trunc('year', t);
    elsif m = 'start of day' then t := date_trunc('day', t);
    elsif m like 'weekday %' then
      n := split_part(m, ' ', 2)::int;            -- 0 = Sunday; move forward to that weekday (or stay)
      t := t + (((n - extract(dow from t)::int) + 7) % 7) * interval '1 day';
    elsif m ~ '^[+-]?[0-9]+(\.[0-9]+)? *(second|minute|hour|day|month|year)s?$' then
      t := t + m::interval;
    end if;
  end loop;
  return t;
end $$;

create or replace function wscompat.sq_date(v text, variadic mods text[] default '{}') returns text
language sql stable as $$ select to_char(wscompat.sq_ts(v, mods), 'YYYY-MM-DD') $$;

create or replace function wscompat.sq_datetime(v text, variadic mods text[] default '{}') returns text
language sql stable as $$ select to_char(wscompat.sq_ts(v, mods), 'YYYY-MM-DD HH24:MI:SS') $$;

create or replace function wscompat.sq_julianday(v text, variadic mods text[] default '{}') returns double precision
language sql stable as $$ select extract(epoch from wscompat.sq_ts(v, mods))::double precision / 86400.0 + 2440587.5 $$;

create or replace function wscompat.sq_strftime(fmt text, v text, variadic mods text[] default '{}') returns text
language plpgsql stable as $$
declare t timestamp := wscompat.sq_ts(v, mods); out text := ''; i int := 1; c text;
begin
  if t is null or fmt is null then return null; end if;
  while i <= length(fmt) loop
    c := substr(fmt, i, 1);
    if c = '%' and i < length(fmt) then
      i := i + 1; c := substr(fmt, i, 1);
      out := out || case c
        when 'Y' then to_char(t, 'YYYY') when 'm' then to_char(t, 'MM') when 'd' then to_char(t, 'DD')
        when 'H' then to_char(t, 'HH24') when 'M' then to_char(t, 'MI') when 'S' then to_char(t, 'SS')
        when 'j' then to_char(t, 'DDD') when 'w' then extract(dow from t)::int::text
        when 'W' then lpad(((extract(doy from t)::int - 1 + 7 - ((extract(dow from t)::int + 6) % 7)) / 7)::text, 2, '0')
        when '%' then '%' else '%' || c end;
    else
      out := out || c;
    end if;
    i := i + 1;
  end loop;
  return out;
end $$;

-- SQLite's ROUND works on floats; Postgres only rounds numerics to n places.
create or replace function wscompat.round(x double precision, n integer) returns double precision
language sql immutable as $$ select round(x::numeric, n)::double precision $$;

create or replace function wscompat.utc_now() returns text
language sql stable as $$ select to_char(now() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') $$;

-- ---------------------------------------------------------------------------
-- WorkDesk
-- ---------------------------------------------------------------------------

create table if not exists workdesk.settings (key text primary key, value text);

create table if not exists workdesk.employees (
  id bigint generated by default as identity primary key,
  name text not null, email text, phone text, designation text,
  role text not null default 'employee',            -- admin | manager | employee
  hourly_cost double precision default 0,
  pin_hash text not null,
  color text default '#6366f1',
  active integer default 1,
  created_at text default wscompat.utc_now()
);

create table if not exists workdesk.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  contact_person text, email text, phone text, gstin text, notes text,
  color text default '#0ea5e9',
  status text default 'active',
  created_at text default wscompat.utc_now(),
  retainer_amount double precision default 0,
  retainer_period text default 'none',
  retainer_start text, retainer_end text, retainer_notes text
);

create table if not exists workdesk.projects (
  id bigint generated by default as identity primary key,
  client_id bigint not null references workdesk.clients(id) on delete cascade,
  name text not null, description text,
  budget double precision default 0, fee double precision default 0,
  status text default 'active',
  start_date text, due_date text,
  created_at text default wscompat.utc_now()
);

create table if not exists workdesk.tasks (
  id bigint generated by default as identity primary key,
  title text not null, description text,
  client_id bigint references workdesk.clients(id) on delete set null,
  project_id bigint references workdesk.projects(id) on delete set null,
  assignee_id bigint references workdesk.employees(id) on delete set null,
  created_by bigint references workdesk.employees(id) on delete set null,
  priority text default 'medium',
  status text default 'todo',
  due_date text,
  estimated_hours double precision default 0,
  created_at text default wscompat.utc_now(),
  updated_at text default wscompat.utc_now(),
  completed_at text,
  self_added integer default 0
);

create table if not exists workdesk.time_logs (
  id bigint generated by default as identity primary key,
  task_id bigint not null references workdesk.tasks(id) on delete cascade,
  employee_id bigint not null references workdesk.employees(id) on delete cascade,
  started_at text not null,
  ended_at text,                                      -- null = timer running
  minutes integer default 0,
  note text,
  source text default 'timer'
);

create table if not exists workdesk.expenses (
  id bigint generated by default as identity primary key,
  title text not null,
  amount double precision not null,
  category text default 'Other',
  date text not null,
  client_id bigint references workdesk.clients(id) on delete set null,
  project_id bigint references workdesk.projects(id) on delete set null,
  task_id bigint references workdesk.tasks(id) on delete set null,
  employee_id bigint references workdesk.employees(id) on delete set null,
  billable integer default 1,
  status text default 'pending',
  notes text,
  receipt_file text, receipt_name text,
  created_at text default wscompat.utc_now()
);

create table if not exists workdesk.comments (
  id bigint generated by default as identity primary key,
  task_id bigint not null references workdesk.tasks(id) on delete cascade,
  employee_id bigint references workdesk.employees(id) on delete set null,
  body text not null,
  created_at text default wscompat.utc_now()
);

create table if not exists workdesk.activity (
  id bigint generated by default as identity primary key,
  ts text default wscompat.utc_now(),
  actor_id bigint references workdesk.employees(id) on delete set null,
  kind text, message text,
  task_id bigint references workdesk.tasks(id) on delete set null,
  client_id bigint references workdesk.clients(id) on delete set null
);

create index if not exists ix_tasks_assignee on workdesk.tasks(assignee_id);
create index if not exists ix_tasks_client on workdesk.tasks(client_id);
create index if not exists ix_logs_task on workdesk.time_logs(task_id);
create index if not exists ix_logs_emp on workdesk.time_logs(employee_id);
create index if not exists ix_exp_client on workdesk.expenses(client_id);

create table if not exists workdesk.notifications (
  id bigint generated by default as identity primary key,
  recipient_id bigint not null references workdesk.employees(id) on delete cascade,
  actor_id bigint references workdesk.employees(id) on delete set null,
  task_id bigint references workdesk.tasks(id) on delete cascade,
  kind text, message text,
  is_read integer default 0,
  created_at text default wscompat.utc_now()
);
create index if not exists ix_notif_recipient on workdesk.notifications(recipient_id, is_read);

create table if not exists workdesk.conversations (
  id bigint generated by default as identity primary key,
  kind text not null default 'direct',                -- direct | office
  name text,
  direct_key text unique,
  created_at text default wscompat.utc_now()
);
create table if not exists workdesk.conversation_members (
  conversation_id bigint not null references workdesk.conversations(id) on delete cascade,
  employee_id bigint not null references workdesk.employees(id) on delete cascade,
  last_read_id bigint default 0,
  primary key (conversation_id, employee_id)
);
create table if not exists workdesk.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references workdesk.conversations(id) on delete cascade,
  sender_id bigint references workdesk.employees(id) on delete set null,
  body text,
  file text, file_name text, file_type text,
  deleted integer default 0,
  created_at text default wscompat.utc_now()
);
create index if not exists ix_msg_conv on workdesk.messages(conversation_id, id);

create table if not exists workdesk.attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references workdesk.employees(id) on delete cascade,
  day text not null,                                  -- India date YYYY-MM-DD
  in_at text not null,                                -- UTC ISO
  out_at text,
  missed_out integer default 0,
  source text default 'self',
  edited_by bigint references workdesk.employees(id) on delete set null
);
create index if not exists ix_att_emp_day on workdesk.attendance(employee_id, day);

create table if not exists workdesk.leaves (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references workdesk.employees(id) on delete cascade,
  day text not null,
  kind text default 'full',
  note text,
  created_by bigint references workdesk.employees(id) on delete set null,
  created_at text default wscompat.utc_now(),
  unique (employee_id, day)
);

create table if not exists workdesk.compliance (
  id bigint generated by default as identity primary key,
  series text,
  title text not null,
  period text,
  category text default 'Other',
  due_date text not null,
  client_id bigint references workdesk.clients(id) on delete cascade,
  assignee_id bigint references workdesk.employees(id) on delete set null,
  recur text default 'none',
  notes text,
  status text default 'pending',
  filed_on text, filed_by bigint references workdesk.employees(id) on delete set null, filed_note text,
  created_by bigint references workdesk.employees(id) on delete set null,
  created_at text default wscompat.utc_now()
);
create index if not exists ix_comp_due on workdesk.compliance(due_date);

create table if not exists workdesk.push_subs (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references workdesk.employees(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  device text,
  created_at text default wscompat.utc_now()
);

create table if not exists workdesk.client_fees (
  id bigint generated by default as identity primary key,
  client_id bigint not null references workdesk.clients(id) on delete cascade,
  date text not null,
  description text not null,
  amount double precision not null,
  status text default 'to_bill',
  task_id bigint references workdesk.tasks(id) on delete set null,
  notes text,
  created_by bigint references workdesk.employees(id) on delete set null,
  created_at text default wscompat.utc_now()
);
create index if not exists ix_fees_client on workdesk.client_fees(client_id, date);

create table if not exists workdesk.notes (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references workdesk.employees(id) on delete cascade,
  kind text not null default 'sticky',
  title text,
  body text default '',
  color text default 'yellow',
  pinned integer default 0,
  shared integer default 0,
  created_at text default wscompat.utc_now(),
  updated_at text default wscompat.utc_now()
);
create index if not exists ix_notes_owner on workdesk.notes(owner_id, kind);

create table if not exists workdesk.suggestions (
  id bigint generated by default as identity primary key,
  author_id bigint references workdesk.employees(id) on delete set null,
  anonymous integer default 0,
  category text default 'Idea',
  title text not null,
  body text,
  status text default 'new',
  reply text, replied_by bigint references workdesk.employees(id) on delete set null, replied_at text,
  created_at text default wscompat.utc_now(),
  updated_at text default wscompat.utc_now()
);

create table if not exists workdesk.holidays (
  id bigint generated by default as identity primary key,
  day text not null unique,
  name text not null
);

-- Cloud additions: change counter for live refresh, pending invoice scans, sign-in throttling
create table if not exists workdesk.live (id integer primary key, seq bigint not null default 0, boot text not null);
insert into workdesk.live (id, seq, boot) values (1, 0, substr(md5(random()::text), 1, 8)) on conflict (id) do nothing;

create table if not exists workdesk.scans (
  file text primary key,
  owner_id bigint references workdesk.employees(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists workdesk.login_attempts (
  employee_id bigint,
  ip text,
  at timestamptz not null default now()
);
create index if not exists ix_login_attempts on workdesk.login_attempts(at);

-- ---------------------------------------------------------------------------
-- ExpenseFlow
-- ---------------------------------------------------------------------------

create table if not exists expenseflow.projects (
  id text primary key,
  name text not null,
  description text,
  color text default '#6366f1',
  budget double precision default 0,
  status text default 'active',
  created_at text default wscompat.sq_datetime('now'),
  updated_at text default wscompat.sq_datetime('now')
);

create table if not exists expenseflow.categories (
  id text primary key,
  name text not null unique,
  icon text default '💼',
  color text default '#6366f1',
  created_at text default wscompat.sq_datetime('now')
);

create table if not exists expenseflow.expenses (
  id text primary key,
  title text not null,
  amount double precision not null,
  currency text default 'USD',
  date text not null,
  project_id text references expenseflow.projects(id) on delete set null,
  category_id text references expenseflow.categories(id) on delete set null,
  description text,
  status text default 'pending',
  paid_by text,
  vendor text,
  tags text default '[]',
  created_at text default wscompat.sq_datetime('now'),
  updated_at text default wscompat.sq_datetime('now')
);

create table if not exists expenseflow.attachments (
  id text primary key,
  expense_id text not null references expenseflow.expenses(id) on delete cascade,
  filename text not null,
  original_name text not null,
  file_size integer,
  mime_type text,
  created_at text default wscompat.sq_datetime('now')
);

create table if not exists expenseflow.api_keys (
  id text primary key,
  name text not null,
  key_hash text not null unique,                      -- sha256 of the key
  permissions text default '["read"]',
  last_used text,
  created_at text default wscompat.sq_datetime('now')
);


-- Defence in depth: RLS on, no policies, so even if a schema were exposed nothing is readable through the API.
do $$
declare r record;
begin
  for r in select schemaname, tablename from pg_tables where schemaname in ('workdesk', 'expenseflow') loop
    execute format('alter table %I.%I enable row level security', r.schemaname, r.tablename);
  end loop;
end $$;

-- Private bucket for receipts, invoice scans, chat attachments and ExpenseFlow attachments.
-- Files are only handed out through short-lived signed links after the server checks who is asking.
insert into storage.buckets (id, name, public, file_size_limit)
values ('workspace', 'workspace', false, 15728640)
on conflict (id) do update set public = false;
